import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useEffect } from 'react'
import {supabase} from '../utils/db'
export default function Home() {

const [posts, setPosts] = useState([])
const [post, setPost] = useState({title: '', content: ''})

useEffect(() => {
 getPosts()



}, [])

async function getPosts() {

  const {data}  = await supabase.from('posts2').select() 

setPosts(data)
console.log('data------->', data)

}


async function handleSubmit(e) {

  e.preventDefault()
await supabase.from('posts2').insert(post).then(() => {
  console.log('inserted')
  getPosts()
}).catch(err => {

  console.log('err', err)
})





}



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>
  <h1>hello nextjs</h1>

<div>

<input type="text" value={post.content} 
onChange={(e) => setPost({...post, content: e.target.value})}

/>

<input type="text" value={post.title} 
onChange={(e) => setPost({...post, title: e.target.value})}

/>

<button
onClick={handleSubmit}
> send post</button>




</div>



</div>


    </div>
  )
}
